# @author : microfat
# @time   : 11/20/22 19:52:38
# @File   : docker-compose.yml

services: 
    flask-apscheduler-test:
        image: flask-apscheduler-test:1.0
        container_name: flask-apscheduler-test
        build:
            context: .
            dockerfile: Services/flask-apscheduler-test/Dockerfile
        volumes:
            - logs:/vol
            - ./:/app
        ports:
            - 8000:8000
        privileged: true
        sysctls:
            net.core.somaxconn: '2000'
        restart: always

volumes: 
    logs:
