# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GeneralResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, success: bool=None, code: int=None, message: str=None, data: Object=None):  # noqa: E501
        """GeneralResponse - a model defined in Swagger

        :param success: The success of this GeneralResponse.  # noqa: E501
        :type success: bool
        :param code: The code of this GeneralResponse.  # noqa: E501
        :type code: int
        :param message: The message of this GeneralResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GeneralResponse.  # noqa: E501
        :type data: Object
        """
        self.swagger_types = {
            'success': bool,
            'code': int,
            'message': str,
            'data': Object
        }

        self.attribute_map = {
            'success': 'success',
            'code': 'code',
            'message': 'message',
            'data': 'data'
        }
        self._success = success
        self._code = code
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GeneralResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The general-response of this GeneralResponse.  # noqa: E501
        :rtype: GeneralResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this GeneralResponse.


        :return: The success of this GeneralResponse.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this GeneralResponse.


        :param success: The success of this GeneralResponse.
        :type success: bool
        """
        if success is None:
            raise ValueError("Invalid value for `success`, must not be `None`")  # noqa: E501

        self._success = success

    @property
    def code(self) -> int:
        """Gets the code of this GeneralResponse.


        :return: The code of this GeneralResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this GeneralResponse.


        :param code: The code of this GeneralResponse.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this GeneralResponse.


        :return: The message of this GeneralResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GeneralResponse.


        :param message: The message of this GeneralResponse.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def data(self) -> Object:
        """Gets the data of this GeneralResponse.


        :return: The data of this GeneralResponse.
        :rtype: Object
        """
        return self._data

    @data.setter
    def data(self, data: Object):
        """Sets the data of this GeneralResponse.


        :param data: The data of this GeneralResponse.
        :type data: Object
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
