# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.patchjobsrequestbody_job import PatchjobsrequestbodyJob  # noqa: F401,E501
from swagger_server.models.postschedulerrequestbody_log import PostschedulerrequestbodyLog  # noqa: F401,E501
from swagger_server import util


class PatchJobsRequestbody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, log: PostschedulerrequestbodyLog=None, job: PatchjobsrequestbodyJob=None):  # noqa: E501
        """PatchJobsRequestbody - a model defined in Swagger

        :param log: The log of this PatchJobsRequestbody.  # noqa: E501
        :type log: PostschedulerrequestbodyLog
        :param job: The job of this PatchJobsRequestbody.  # noqa: E501
        :type job: PatchjobsrequestbodyJob
        """
        self.swagger_types = {
            'log': PostschedulerrequestbodyLog,
            'job': PatchjobsrequestbodyJob
        }

        self.attribute_map = {
            'log': 'log',
            'job': 'job'
        }
        self._log = log
        self._job = job

    @classmethod
    def from_dict(cls, dikt) -> 'PatchJobsRequestbody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The patch-jobs-requestbody of this PatchJobsRequestbody.  # noqa: E501
        :rtype: PatchJobsRequestbody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def log(self) -> PostschedulerrequestbodyLog:
        """Gets the log of this PatchJobsRequestbody.


        :return: The log of this PatchJobsRequestbody.
        :rtype: PostschedulerrequestbodyLog
        """
        return self._log

    @log.setter
    def log(self, log: PostschedulerrequestbodyLog):
        """Sets the log of this PatchJobsRequestbody.


        :param log: The log of this PatchJobsRequestbody.
        :type log: PostschedulerrequestbodyLog
        """
        if log is None:
            raise ValueError("Invalid value for `log`, must not be `None`")  # noqa: E501

        self._log = log

    @property
    def job(self) -> PatchjobsrequestbodyJob:
        """Gets the job of this PatchJobsRequestbody.


        :return: The job of this PatchJobsRequestbody.
        :rtype: PatchjobsrequestbodyJob
        """
        return self._job

    @job.setter
    def job(self, job: PatchjobsrequestbodyJob):
        """Sets the job of this PatchJobsRequestbody.


        :param job: The job of this PatchJobsRequestbody.
        :type job: PatchjobsrequestbodyJob
        """
        if job is None:
            raise ValueError("Invalid value for `job`, must not be `None`")  # noqa: E501

        self._job = job
