openapi: 3.0.3
info:
  title: flask-apscheduler
  version: 1.0.0
servers:
- url: "{protocol}://0.0.0.0:{port}"
  variables:
    protocol:
      enum:
      - http
      - https
      default: http
    port:
      enum:
      - "8000"
      default: "8000"
tags:
- name: test
  description: 测试
paths: {}
components: {}

